### PR TITLE
Fix typos, add a readme stub

### PR DESCRIPTION
**Pull request by dominykas**
##### Checklist

- [x] commit message follows [commit guidelines]

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by BethGriggs — APPROVED** [review]

**Comment by dominykas** [comment]
@mhdawson I don't have the permission to merge this - am I in the right teams?

**Comment by mhdawson** [comment]
@dominykas checking..

**Comment by mhdawson** [comment]
@dominykas you were in the right group, but I'd not assigned the right privileges, fixed.

**Comment by dominykas** [comment]
Thanks!

**Pull request merged**
